### PR TITLE
🚀

### PR DESCRIPTION
**Pull request by ELI7VH**

### CODE REVIEW

**Comment by tannercollin** [comment]
Bug:
Screenshot from 2020-08-20 22-11-51

**Comment by ELI7VH** [comment]
@tannercollin can you recap what the bug is? Is it the space? between the form and the footer?

**Comment by ELI7VH** [comment]
@tannercollin or I can just use my eyes.  Fixed!

**Comment by tannercollin** [comment]
Merged! thx bb

**Pull request merged**
